[phases.setup]
nixPkgs = [
  "php82",
  "composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.openssl",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.bcmath"
]

[phases.build]
cmds = [
  "/nix/var/nix/profiles/default/bin/composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[postdeploy]
cmd = "php artisan key:generate && php artisan migrate --force && php artisan storage:link"
